// TrueType -> M5GFX (Adafruit GFX) bitmap font.
//
// Written here rather than pulled in because FreeType was already installed
// and the format is small: per glyph, a 1-bit bitmap packed MSB-first as one
// continuous stream with NO padding between rows, plus metrics. The stock
// Free* faces M5GFX ships are in exactly this layout.
//
// Build:  cc -O2 -o tools/fontconvert tools/fontconvert.c \
//             -I$(brew --prefix freetype)/include/freetype2 \
//             -L$(brew --prefix freetype)/lib -lfreetype
// Use:    tools/fontconvert Anton-Regular.ttf 96 Anton96 > src/font_anton96.h
#include <ft2build.h>
#include FT_FREETYPE_H

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define FIRST 0x20
#define LAST 0x7E

int main(int argc, char **argv) {
  if (argc < 4) {
    fprintf(stderr, "usage: %s font.ttf pixelsize Name\n", argv[0]);
    return 1;
  }
  const char *path = argv[1];
  const int size = atoi(argv[2]);
  const char *name = argv[3];

  FT_Library lib;
  FT_Face face;
  if (FT_Init_FreeType(&lib)) {
    fprintf(stderr, "FT_Init_FreeType failed\n");
    return 1;
  }
  if (FT_New_Face(lib, path, 0, &face)) {
    fprintf(stderr, "cannot open %s\n", path);
    return 1;
  }
  if (FT_Set_Pixel_Sizes(face, 0, size)) {
    fprintf(stderr, "cannot set size %d\n", size);
    return 1;
  }

  const int count = LAST - FIRST + 1;
  unsigned char *bitmap = NULL;
  size_t cap = 0, len = 0;

  struct {
    unsigned offset, w, h, adv;
    int xo, yo;
  } *g = calloc(count, sizeof(*g));

  for (int c = FIRST; c <= LAST; c++) {
    if (FT_Load_Char(face, c, FT_LOAD_TARGET_MONO | FT_LOAD_RENDER)) {
      fprintf(stderr, "glyph %d failed\n", c);
      return 1;
    }
    FT_Bitmap *bm = &face->glyph->bitmap;
    const int i = c - FIRST;
    g[i].offset = (unsigned)len;
    g[i].w = bm->width;
    g[i].h = bm->rows;
    g[i].adv = (unsigned)(face->glyph->advance.x >> 6);
    g[i].xo = face->glyph->bitmap_left;
    g[i].yo = -face->glyph->bitmap_top;

    // Repack: FreeType pads every row to a byte boundary, the GFX format does
    // not. Getting this wrong shears each glyph progressively down its height.
    const size_t bits = (size_t)bm->width * bm->rows;
    const size_t bytes = (bits + 7) / 8;
    if (len + bytes + 1 > cap) {
      cap = (len + bytes + 1) * 2;
      bitmap = realloc(bitmap, cap);
    }
    size_t bit = 0;
    memset(bitmap + len, 0, bytes);
    for (unsigned y = 0; y < bm->rows; y++) {
      for (unsigned x = 0; x < bm->width; x++) {
        const unsigned char byte = bm->buffer[y * bm->pitch + (x >> 3)];
        if (byte & (0x80 >> (x & 7))) {
          bitmap[len + (bit >> 3)] |= (unsigned char)(0x80 >> (bit & 7));
        }
        bit++;
      }
    }
    len += bytes;
  }

  const int yadv = (int)(face->size->metrics.height >> 6);

  printf("// Generated by tools/fontconvert.c from %s at %d px.\n", path, size);
  printf("// Anton is licensed under the SIL Open Font License 1.1;\n");
  printf("// see assets/fonts/Anton-OFL.txt. Do not edit by hand.\n");
  printf("#pragma once\n\n#include <M5Unified.h>\n\n");
  printf("namespace tabulous {\nnamespace fontdata {\n\n");

  printf("static const uint8_t %sBitmaps[] = {\n ", name);
  for (size_t i = 0; i < len; i++) {
    printf(" 0x%02X,", bitmap[i]);
    if ((i & 11) == 11) printf("\n ");
  }
  printf("\n};\n\n");

  printf("static const lgfx::v1::GFXglyph %sGlyphs[] = {\n", name);
  for (int i = 0; i < count; i++) {
    printf("  { %6u, %3u, %3u, %3u, %4d, %4d },  // 0x%02X", g[i].offset, g[i].w,
           g[i].h, g[i].adv, g[i].xo, g[i].yo, FIRST + i);
    const int c = FIRST + i;
    if (c > 0x20 && c < 0x7F) printf(" '%c'", c);
    printf("\n");
  }
  printf("};\n\n");

  printf("// const_cast because GFXfont predates const-correctness; nothing\n");
  printf("// writes through these, and the arrays stay in flash.\n");
  printf("inline const lgfx::v1::GFXfont %s(\n", name);
  printf("    const_cast<uint8_t *>(%sBitmaps),\n", name);
  printf("    const_cast<lgfx::v1::GFXglyph *>(%sGlyphs),\n", name);
  printf("    0x%02X, 0x%02X, %d);\n\n", FIRST, LAST, yadv);
  printf("}  // namespace fontdata\n}  // namespace tabulous\n");

  fprintf(stderr, "%s: %zu bytes of bitmap, yAdvance %d\n", name, len, yadv);
  return 0;
}
